// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://example.com/terms/",
        "contact": {
            "name": "Pankaj Kumar",
            "url": "https://example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Responds with pong",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/poll/icmp": {
            "post": {
                "description": "APIs helps to write poll parameter into db",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Polling Status update",
                "parameters": [
                    {
                        "description": "ICMP Request body",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.ICMPReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.ICMPReq"
                        }
                    }
                }
            }
        },
        "/api/poll/snmp": {
            "post": {
                "description": "APIs helps to write poll parameter into db",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Polling Status update",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/M.SNMPReq"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "M.ICMPReq": {
            "type": "object",
            "required": [
                "ci_id",
                "poll_addr"
            ],
            "properties": {
                "ci_id": {
                    "type": "string"
                },
                "input_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/M.InputStat"
                    }
                },
                "params": {
                    "$ref": "#/definitions/M.PINGParams"
                },
                "poll_addr": {
                    "type": "string"
                }
            }
        },
        "M.InputStat": {
            "type": "object",
            "properties": {
                "dn": {
                    "type": "string"
                },
                "oid": {
                    "type": "string"
                }
            }
        },
        "M.PINGParams": {
            "type": "object",
            "required": [
                "poll_period",
                "poll_type"
            ],
            "properties": {
                "mib_profile": {
                    "type": "string"
                },
                "packsiz": {
                    "type": "integer"
                },
                "parent_ci_id": {
                    "type": "string"
                },
                "poll_addr": {
                    "type": "string"
                },
                "poll_addr_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_period": {
                    "type": "integer",
                    "enum": [
                        5,
                        60,
                        300
                    ]
                },
                "poll_type": {
                    "type": "string",
                    "enum": [
                        "ping"
                    ]
                }
            }
        },
        "M.SNMPParams": {
            "type": "object",
            "required": [
                "poll_period",
                "poll_type"
            ],
            "properties": {
                "ci_category": {
                    "type": "string"
                },
                "ci_name": {
                    "type": "string"
                },
                "custom_type": {
                    "description": "OidIndex   string ` + "`" + `json:\"oidIndex\"` + "`" + `",
                    "type": "string"
                },
                "memory_size": {
                    "type": "integer"
                },
                "mib_profile": {
                    "type": "string"
                },
                "parent_ci_id": {
                    "type": "string"
                },
                "poll_addr": {
                    "type": "string"
                },
                "poll_addr_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_period": {
                    "type": "integer",
                    "enum": [
                        60,
                        300
                    ]
                },
                "poll_type": {
                    "type": "string",
                    "enum": [
                        "snmp"
                    ]
                },
                "speed": {
                    "type": "integer"
                }
            }
        },
        "M.SNMPReq": {
            "type": "object",
            "required": [
                "ci_id",
                "login_profileid",
                "poll_addr"
            ],
            "properties": {
                "ci_id": {
                    "type": "string"
                },
                "input_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/M.InputStat"
                    }
                },
                "login_profileid": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/M.SNMPParams"
                },
                "poll_addr": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Probe",
	Description:      "agent",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
