// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/pnkj-kmr/probe",
        "contact": {
            "name": "Pankaj Kumar",
            "url": "https://github.com/pnkj-kmr",
            "email": "pnkj3092@gmail.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/": {
            "get": {
                "description": "Responds with pong",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "pong",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/credential/http": {
            "post": {
                "description": "help to save login profile or device profile creds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Save Login Credential",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.AuthHTTP"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.AuthHTTP"
                        }
                    }
                }
            }
        },
        "/api/credential/sftp": {
            "post": {
                "description": "help to save login profile or device profile creds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Save Login Credential",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.AuthSFTP"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.AuthSFTP"
                        }
                    }
                }
            }
        },
        "/api/credential/snmp": {
            "post": {
                "description": "help to save login profile or device profile creds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Save Login Credential",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.AuthSNMP"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.AuthSNMP"
                        }
                    }
                }
            }
        },
        "/api/credential/ssh": {
            "post": {
                "description": "help to save login profile or device profile creds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Save Login Credential",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.AuthSSH"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.AuthSSH"
                        }
                    }
                }
            }
        },
        "/api/credential/telnet": {
            "post": {
                "description": "help to save login profile or device profile creds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Save Login Credential",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.AuthTELNET"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.AuthTELNET"
                        }
                    }
                }
            }
        },
        "/api/credential/{credential_type}/": {
            "get": {
                "description": "total count",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Total records of credential",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: snmp / ssh / telnet / sftp / http",
                        "name": "credential_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete all",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Delete all credentials for profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: snmp / ssh / telnet / sftp / http",
                        "name": "credential_type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/credential/{credential_type}/{id}": {
            "get": {
                "description": "creential profile view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Get credential record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: snmp / ssh / telnet / sftp / http",
                        "name": "credential_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "credential id (login/device profile id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete one",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credential"
                ],
                "summary": "Delete credential for profile id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: snmp / ssh / telnet / sftp / http",
                        "name": "credential_type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "credential id (login/device profile id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/dashboard/data": {
            "get": {
                "description": "helps to get the current save stats into system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get saved statistics params",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ICMP collection table",
                        "name": "table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "CI_ID to query",
                        "name": "cid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/dashboard/model": {
            "get": {
                "description": "stats db models",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get search model name",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dashboard.SearchModel"
                            }
                        }
                    }
                }
            }
        },
        "/api/dashboard/poll": {
            "get": {
                "description": "helps to get the current polling status along with poll result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get polling stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dashboard.PollStat"
                            }
                        }
                    }
                }
            }
        },
        "/api/dashboard/resource": {
            "get": {
                "description": "total resource which aligned to poll",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get resource stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dashboard.ResourceStats"
                        }
                    }
                }
            }
        },
        "/api/dashboard/system": {
            "get": {
                "description": "cpu, memory and disk usage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get system stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dashboard.SystemStats"
                        }
                    }
                }
            }
        },
        "/api/poll/icmp": {
            "post": {
                "description": "APIs helps to write poll parameter into db",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Polling Status update",
                "parameters": [
                    {
                        "description": "ICMP Request body",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.ICMPReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.ICMPReq"
                        }
                    }
                }
            }
        },
        "/api/poll/snmp": {
            "post": {
                "description": "APIs helps to write poll parameter into db",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Polling Status update",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/M.SNMPReq"
                        }
                    }
                }
            }
        },
        "/api/poll/{type}/{pollPeriod}": {
            "get": {
                "description": "get totel record of poll config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Poll Config Total Count",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: icmp / snmp",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Poll Period - like: 60/300",
                        "name": "pollPeriod",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "deleting the poll config records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Delete All Poll Config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: icmp / snmp",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Poll Period - like: 60/300",
                        "name": "pollPeriod",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/poll/{type}/{pollPeriod}/{id}": {
            "get": {
                "description": "get poll config data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Poll Config Get View",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: icmp / snmp",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Poll Period - like: 60/300",
                        "name": "pollPeriod",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CI ID of resource",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "poll config",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete poll config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Poll"
                ],
                "summary": "Poll Config Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type: icmp / snmp",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Poll Period - like: 60/300",
                        "name": "pollPeriod",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CI ID of resource",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/profile/agent/info": {
            "get": {
                "description": "Probe configuration detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get Agent Info",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/profile/agent/token": {
            "post": {
                "description": "Probe configuration update",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Update Agent Token",
                "parameters": [
                    {
                        "description": "Token Payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.TokenPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/profile.TokenPayload"
                        }
                    }
                }
            }
        },
        "/api/profile/env": {
            "get": {
                "description": "Probe env detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get Env Info",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "description": "Probe env detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Save Env Info",
                "parameters": [
                    {
                        "description": "Request Payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/M.Env"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/M.Env"
                        }
                    }
                }
            }
        },
        "/api/profile/process/status": {
            "get": {
                "description": "Probe thread process detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get Processes Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/M.ProcessBeat"
                            }
                        }
                    }
                }
            }
        },
        "/api/profile/text/decrypt": {
            "post": {
                "description": "decryption of payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Decrypt a text",
                "parameters": [
                    {
                        "description": "Request Payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.TextPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/profile.TextPayload"
                        }
                    }
                }
            }
        },
        "/api/profile/text/encrypt": {
            "post": {
                "description": "encryption",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Encryting the text",
                "parameters": [
                    {
                        "description": "Request Payload",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.TextPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/profile.TextPayload"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "M.AuthHTTP": {
            "type": "object",
            "required": [
                "login_profileid",
                "name",
                "protocol_type"
            ],
            "properties": {
                "credentialtype": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "login_profileid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "no_of_custom_pairs": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol_type": {
                    "enum": [
                        "http",
                        "https"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/M.ProtocolType"
                        }
                    ]
                },
                "retries": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "M.AuthSFTP": {
            "type": "object",
            "required": [
                "login_profileid",
                "name",
                "protocol_type"
            ],
            "properties": {
                "credentialtype": {
                    "type": "string"
                },
                "login_profileid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol_type": {
                    "enum": [
                        "sftp"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/M.ProtocolType"
                        }
                    ]
                },
                "retries": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "M.AuthSNMP": {
            "type": "object",
            "required": [
                "login_profileid",
                "name",
                "protocol_type",
                "version"
            ],
            "properties": {
                "auth_pass": {
                    "type": "string"
                },
                "auth_type": {
                    "type": "string"
                },
                "community": {
                    "type": "string"
                },
                "context_engine_id": {
                    "type": "string"
                },
                "context_name": {
                    "type": "string"
                },
                "login_profileid": {
                    "type": "string"
                },
                "max_oids": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "priv_pass": {
                    "type": "string"
                },
                "priv_type": {
                    "type": "string"
                },
                "protocol_type": {
                    "enum": [
                        "snmp"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/M.ProtocolType"
                        }
                    ]
                },
                "request_type": {
                    "$ref": "#/definitions/M.SNMPOperation"
                },
                "retries": {
                    "type": "integer"
                },
                "security_level": {
                    "type": "string"
                },
                "timeout": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "version": {
                    "$ref": "#/definitions/M.SNMPVersion"
                },
                "wcommunity": {
                    "type": "string"
                }
            }
        },
        "M.AuthSSH": {
            "type": "object",
            "required": [
                "login_profileid",
                "name",
                "protocol_type"
            ],
            "properties": {
                "credentialtype": {
                    "type": "string"
                },
                "linked_profiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/M.LinkedProfile"
                    }
                },
                "login_profileid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol_type": {
                    "enum": [
                        "ssh"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/M.ProtocolType"
                        }
                    ]
                },
                "retries": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "M.AuthTELNET": {
            "type": "object",
            "required": [
                "login_profileid",
                "name",
                "protocol_type"
            ],
            "properties": {
                "credentialtype": {
                    "type": "string"
                },
                "linked_profiles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/M.LinkedProfile"
                    }
                },
                "login_profileid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "protocol_type": {
                    "enum": [
                        "telnet"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/M.ProtocolType"
                        }
                    ]
                },
                "retries": {
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "M.Env": {
            "type": "object",
            "required": [
                "API_PORT",
                "NO_WORKER_THREADS"
            ],
            "properties": {
                "API_PORT": {
                    "type": "integer"
                },
                "API_SERVER": {
                    "description": "api server flag",
                    "type": "boolean"
                },
                "DEBUG": {
                    "description": "system parameter",
                    "type": "boolean"
                },
                "EXPORTER_DBDUMP": {
                    "type": "boolean"
                },
                "EXPORTER_KAFKA": {
                    "type": "boolean"
                },
                "EXPORTER_WEBHOOK": {
                    "description": "exporter flag",
                    "type": "boolean"
                },
                "ICMP_POLLING": {
                    "description": "poller flags",
                    "type": "boolean"
                },
                "KAFAK_MAX_MESSAGE_SIZE": {
                    "type": "integer"
                },
                "KAFAK_TOPIC_PARTITIONS": {
                    "type": "integer"
                },
                "KAFKA_DEFAULT_TOPIC": {
                    "description": "addition kafka flag",
                    "type": "string"
                },
                "NO_WORKER_THREADS": {
                    "type": "integer"
                },
                "PROCESS_MAX_RESTARTS": {
                    "type": "integer"
                },
                "SNMP_POLLING": {
                    "type": "boolean"
                }
            }
        },
        "M.ICMPReq": {
            "type": "object",
            "required": [
                "ci_id",
                "poll_addr"
            ],
            "properties": {
                "ci_id": {
                    "type": "string"
                },
                "input_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/M.InputStat"
                    }
                },
                "params": {
                    "$ref": "#/definitions/M.PINGParams"
                },
                "poll_addr": {
                    "type": "string"
                }
            }
        },
        "M.InputStat": {
            "type": "object",
            "properties": {
                "dn": {
                    "type": "string"
                },
                "oid": {
                    "type": "string"
                }
            }
        },
        "M.LinkedProfile": {
            "type": "object",
            "required": [
                "login_profileid",
                "protocol_type"
            ],
            "properties": {
                "login_profileid": {
                    "type": "string"
                },
                "protocol_type": {
                    "$ref": "#/definitions/M.ProtocolType"
                }
            }
        },
        "M.PINGParams": {
            "type": "object",
            "required": [
                "poll_period",
                "poll_type"
            ],
            "properties": {
                "mib_profile": {
                    "type": "string"
                },
                "packsiz": {
                    "type": "integer"
                },
                "parent_ci_id": {
                    "type": "string"
                },
                "poll_addr": {
                    "type": "string"
                },
                "poll_addr_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_period": {
                    "type": "integer",
                    "enum": [
                        60,
                        300
                    ]
                },
                "poll_type": {
                    "type": "string",
                    "enum": [
                        "ping"
                    ]
                }
            }
        },
        "M.ProcessBeat": {
            "type": "object",
            "properties": {
                "counter": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "et": {
                    "type": "string"
                },
                "given": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "polled": {
                    "type": "integer"
                },
                "st": {
                    "type": "string"
                },
                "t": {
                    "type": "string"
                }
            }
        },
        "M.ProtocolType": {
            "type": "string",
            "enum": [
                "snmp",
                "http",
                "https",
                "ssh",
                "sftp",
                "telnet"
            ],
            "x-enum-varnames": [
                "SNMPType",
                "HTTPType",
                "HTTPSType",
                "SSHType",
                "SFTPType",
                "TELNETType"
            ]
        },
        "M.SNMPOperation": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "GET",
                "WALK",
                "BULKWALK"
            ]
        },
        "M.SNMPParams": {
            "type": "object",
            "required": [
                "poll_period",
                "poll_type"
            ],
            "properties": {
                "ci_category": {
                    "type": "string"
                },
                "ci_name": {
                    "type": "string"
                },
                "custom_type": {
                    "description": "OidIndex   string ` + "`" + `json:\"oidIndex\"` + "`" + `",
                    "type": "string"
                },
                "memory_size": {
                    "type": "integer"
                },
                "mib_profile": {
                    "type": "string"
                },
                "parent_ci_id": {
                    "type": "string"
                },
                "poll_addr": {
                    "type": "string"
                },
                "poll_addr_list": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_period": {
                    "type": "integer",
                    "enum": [
                        60,
                        300
                    ]
                },
                "poll_type": {
                    "type": "string",
                    "enum": [
                        "snmp"
                    ]
                },
                "speed": {
                    "type": "integer"
                }
            }
        },
        "M.SNMPReq": {
            "type": "object",
            "required": [
                "ci_id",
                "login_profileid",
                "poll_addr"
            ],
            "properties": {
                "ci_id": {
                    "type": "string"
                },
                "input_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/M.InputStat"
                    }
                },
                "login_profileid": {
                    "type": "string"
                },
                "params": {
                    "$ref": "#/definitions/M.SNMPParams"
                },
                "poll_addr": {
                    "type": "string"
                }
            }
        },
        "M.SNMPVersion": {
            "type": "string",
            "enum": [
                "1",
                "2c",
                "3"
            ],
            "x-enum-varnames": [
                "VERSION1",
                "VERSION2C",
                "VERSION3"
            ]
        },
        "dashboard.CPU": {
            "type": "object",
            "properties": {
                "cores": {
                    "type": "integer"
                },
                "usage": {
                    "type": "number"
                }
            }
        },
        "dashboard.Disk": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "string"
                },
                "used": {
                    "type": "string"
                },
                "used_percent": {
                    "type": "number"
                }
            }
        },
        "dashboard.Memory": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "string"
                },
                "used": {
                    "type": "string"
                },
                "used_percent": {
                    "type": "number"
                }
            }
        },
        "dashboard.PollStat": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "polled": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dashboard.ResourceStats": {
            "type": "object",
            "properties": {
                "stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dashboard.PollStat"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dashboard.SearchModel": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "dashboard.SystemStats": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/dashboard.CPU"
                },
                "disk": {
                    "$ref": "#/definitions/dashboard.Disk"
                },
                "memory": {
                    "$ref": "#/definitions/dashboard.Memory"
                }
            }
        },
        "profile.TextPayload": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                }
            }
        },
        "profile.TokenPayload": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Probe",
	Description:      "agent",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
